name: Daily Calendar Reminder

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3 -> v4로 업데이트
      - name: Set up Python
        uses: actions/setup-python@v5 # v4 -> v5로 업데이트
        with:
          python-version: '3.11' # 안정적인 최신 버전 사용
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python send_reminders.py
